name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: 'Mayankpaliwal09'
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push to output branch
        run: |
          git checkout -B output
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake SVG"
          git push --force origin output
    # End of steps
